common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from spotipie.views import base_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('spotipie/', include('spotipie.urls')),
    path('common/', include('common.urls')),
    path('', base_views.index, name='index')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

spotipie/urls.py
from django.urls import path
from .views import base_views, search_views, track_views


app_name = 'spotipie'

urlpatterns = ([
    # base_views.py
    path('', base_views.index, name='index'),
    path('callback/', base_views.callback, name='callback'),

    # search_views.py
    path('search/', search_views.search, name='search'),

    # track_views.py
    path('track/<str:track_id>/', track_views.play_track, name='play_track'),
    path('my_library/', track_views.my_library, name='my_library'),
    path('my_library/delete/<str:track_uri>/', track_views.delete_track, name='delete_track'),
])

spotipie/models.py
import requests
from django.db import models

class Song(models.Model):
    name = models.CharField(max_length=100)
    artist = models.CharField(max_length=100)
    album_cover = models.ImageField(upload_to='album_covers/', null=True, blank=True)
    audio_file = models.FileField(upload_to='songs/', blank=True, null=True)

    def __str__(self):
        return self.name

spotipie/forms.py
from django import forms
from .models import Song

class SongForm(forms.ModelForm):
    class Meta:
        model = Song
        fields = ['name', 'artist', 'album_cover']

# forms.py 파일은 폼을 정의하는 역할. 사용자로 부터 입력 받기 위한 구조 제공

spotipie/views/base_views.py
import os
import requests
from django.shortcuts import redirect, HttpResponse, render
from env.env import CLIENT_ID, CLIENT_SECRET
from dotenv import load_dotenv
from django.conf import settings

load_dotenv()

def index(request):
    return render(request, 'spotipie/music_list.html')

def favicon_view(request):
    return HttpResponse(status=204)  # 빈 응답을 반환
def callback(request):
    code = request.GET.get('code')
    # 스포티파이가 제공하는 인증 코드
    if code:
        response = requests.post('https://accounts.spotify.com/api/token', data={
            'grant_type': 'authorization_code',
            'code': request.GET.get('code'),
            # 스포티파이 인증 서버에서 리디렉션 uri를 통해 받은 인증 코드
            'redirect_uri': 'http://localhost:8000/spotipie/callback/',
            # Spotify Developer 대시보드에 등록된 리디렉션 URI
            # 인증 결과 처리하는 전용 엔드포인트 => 로그인 성공시 여기로 인증 결과 돌려보내 줌(인증코드 포함)
            # 엔드포인트 : 웹 api에서 특정 리소스나 기능에 접근하기 위한 url 경로
            'client_id': CLIENT_ID,
            'client_secret': CLIENT_SECRET
            # 하드코딩 X => 보안문제!
        })
        response_data = response.json()
        # 응답을 JSON 형식으로 변환한다.
        access_token = response_data.get('access_token')
        if access_token:
            request.session['access_token'] = access_token
            # 엑세스 토큰을 Django 세션에 저장한다.
            # 엑세스 토근은 api 요청에 필요한 인증 정보 포함함.
            # HttpResponse: 엑세스 토큰 포함한 응답을 클라이언트에게 반환
            return redirect('spotipie:index')
        return HttpResponse('No access token received')
    return HttpResponse('No code received')
# access 토근 받기, callback 처리
#역할: Spotify의 OAuth 인증 프로세스에서 인증 코드를 액세스 토큰으로 교환합니다
# 함수는 Spotify의 OAuth 인증 프로세스에서 중요한 역할을 하며, 사용자 인증 후 Spotify API와의 상호작용을 설정하는 데 사용됨.
# 이 함수의 주요 기능은 인증 코드를 받아 액세스 토큰으로 교환하고 이를 세션에 저장하여 API 요청에 사용할 수 있게 하는 것.

spotipie/views/search_views.py
import requests
from django.shortcuts import HttpResponse, render


def search_tracks(query, access_token):
    # 트랙을 검색하는 기능 / api와 상호작용
    # query는 검색할 트랙 제목이나 아티스트 이름과 같은 문자열을 뜻함
    # access_token : spotify에 요청할 때 필요한 인증 토큰
    url = "https://api.spotify.com/v1/search"
    # spotify의 검색 api 엔드포인트 url
    # /v1/search 스포티파이의 검색 경로
    headers = {
        "Authorization": f"Bearer {access_token}"
        # api 호출 시 필요로 하는 http 헤더를 설정
    }
    params = {
        # 쿼리 파라미터
        "q": query,
        "type": "track",
        "limit": 10
    }
    response = requests.get(url, headers=headers, params=params)
    #  클라이언트와 서버가 데이터를 주고받을 때 중요한 정보를 전달
    # request 모듈 -> http 요청을 쉽게 처리할 수 있는 라이브러리
    # get()함수 -> get요청을 보낼 때 사용한다.
    search_results = response.json()
    #  스포티파이 api로부터 반환된 json 응답을 담고 있는 딕셔너리 -> 검색 결과 관련 다양한 데이터 들어있다
    tracks = search_results.get('tracks', {}).get('items', [])
    # tracks vs items -> 노트북 사진 참고

    # 아티스트 정보 추가
    for track in tracks:
        artist_id = track['artists'][0]['id']
        # 첫 번째 트랙의 아티스트 id(정보) 가져온다
        artist_info = get_artist_info(artist_id, access_token)
        track['artist_image'] = artist_info.get('images', [{}])[0].get('url', '')
        # tracks 리스트는 search_results 안에 존재. track에 추가된 아티스트 이미지는 search_results에 추가됨
        # tracks 내부의 track에 아티스트 이미지 추가

    return search_results

def search(request):
    # 사용자 인터페이와 관련된 로직 처리
    query = request.GET.get('query', '').strip()
    # request.GET은 get요청으로 전달된 파라미터를 가져옴
    # 여기서는 쿼리 파라미터에서 "query" 값 가져옴. 없으면 공백
    access_token = request.session.get('access_token')
    #  request.session은 장고에서 제공하는 세션을 관리하는 속성이다.
    #  세션 존재하지 않을 시 기본적으로 none반환

    if not access_token:
        return HttpResponse('Access token not found')

    if query:
        search_results = search_tracks(query, access_token)
        # query 값이 존재한다면 search_tracks 함수를 호출해서 spotify api에서 트랙을 검색
        # get요청,결과 반환
        # search_results: 이 변수는 Spotify API에서 반환된 JSON 응답을 담고 있는 딕셔너리입니다.
        tracks = search_results.get('tracks', {}).get('items', [])
        # search_results 에서 tracks와 items 의 키 값 추출, 추출값을 tracks에 저장.
        # get 메서드는 딕셔너리에서 값을 추출하는 데 사용된다.
        # 위 코드를 search_tracks에서 가져오면 안되나?(어차피 동일한데..) -> 함수의 역할과 독립성
        #  tracks = search_tracks(query, access_token) 이렇게 써도 되긴 함. 그런데 나중에 유지보수나 확장성에서 불리함
    else:
        tracks = []

    return render(request, 'spotipie/search_result.html', {'tracks': tracks, 'access_token': access_token})

def get_artist_info(artist_id, access_token):
    url = f"https://api.spotify.com/v1/artists/{artist_id}"
    headers = {
        "Authorization": f"Bearer {access_token}"
    }
    response = requests.get(url, headers=headers)
    return response.json()

spotipie/views/track_views.py
import requests
import json
# json 모듈을 임포트
from django.shortcuts import HttpResponse, render
from django.http import JsonResponse
import urllib.parse

def play_track(request, track_id):
    # 특정 트랙의 상세 정보를 표시
    access_token = request.session.get('access_token')

    if not access_token:
        return HttpResponse('Access token not found')

    # Spotify에서 트랙 정보를 가져온다.
    headers = {
        'Authorization': f'Bearer {access_token}'
    }
    response = requests.get(f'https://api.spotify.com/v1/tracks/{track_id}', headers=headers)
    track = response.json()

    return render(request, 'spotipie/play_track.html', {
        'track_id': track_id,
        'track': track,
        'access_token': access_token
    })

def my_library(request):
    # my_library.html 템플릿을 렌더링
    access_token = request.session.get('access_token')
    # 엑세스 코드 전달해 줘야만 '내 라이브러리' 에서 곡 재생 가능함
    return render(request, 'spotipie/my_library.html', {'access_token': access_token})


def delete_track(request, track_uri):
    if request.method == 'DELETE':
        decoded_uri = urllib.parse.unquote(track_uri)
        # track_uri를 디코딩함
        print(decoded_uri)  # 디버그용 로그
        # 여기서 decoded_uri를 사용해 삭제 로직을 처리
        return JsonResponse({'message': '곡이 삭제되었습니다!'}, status=200)
    return JsonResponse({'error': '잘못된 요청입니다.'}, status=400)

templates/spotipie/music_list.html
{% extends 'base.html' %}
{% block content %}
<div style="display: flex;">
    <!-- 사이드바 -->
    <div style="width: 220px; background-color: #f0f0f0; padding: 20px; height: 100vh; display: flex; flex-direction: column; justify-content: space-between;">
        <ul style="list-style-type: none; padding: 0; margin: 0;">
            <li>
                <a href="https://accounts.spotify.com/authorize?client_id=3b4032b2dd834248a0beba5614647b9b&response_type=code&redirect_uri=http://localhost:8000/spotipie/callback/&scope=user-library-read%20streaming%20user-modify-playback-state"
                   style="text-decoration: none; color: #333; font-size: 1.2em; display: block; margin: 20px 0;">
                    spotipie 토큰
                </a>
            </li>
            <li>
                <a href="{% url 'spotipie:index' %}" style="text-decoration: none; color: #333; font-size: 1.2em; display: block; margin: 20px 0;">
                    홈
                </a>
            </li>
            <li>
                <a href="{% url 'spotipie:my_library'%}" style="text-decoration: none; color: #333; font-size: 1.2em; display: block; margin: 20px 0;">
                    내 라이브러리
                </a>
            </li>
        </ul>
    </div>

    <!-- 콘텐츠 영역 -->
    <div style="flex: 1; padding: 20px;">
        <h1 style="text-align: center;">SPOTIPIE</h1>
        <form method="get" action="{% url 'spotipie:search' %}" class="d-flex mb-4">
            <input type="text" name="query" placeholder="노래 제목 또는 아티스트를 입력하세요" class="form-control me-2">
<!--            폼 태그는 웹 페이지에서 사용자로부터 데이터를 입력받고 서버로 전송하는 역할을 함-->
            <button type="submit" class="ivory-button">검색</button>
        </form>
    </div>
</div>
{% endblock %}

templates/spotipie/my_library.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container-fluid">
    <h1 class="text-center">내 라이브러리</h1>
    <div id="savedTracksContainer" class="row"></div>
</div>
{% endblock %}

{% block script %}
<script src="https://sdk.scdn.co/spotify-player.js"></script>
<!--sdk: 곡 검색, 재생목록 만들기, 곡 재생 기능-->
<script>
    let isPlayerReady = false; // 플레이어 준비 상태
    let player; // Spotify Player의 인스턴스
    let deviceId = null; // Spotify 디바이스 ID

    const accessToken = "{{ access_token }}"; // Django 템플릿에서 액세스 토큰을 가져온다

    // Spotify 플레이어를 초기화하는 부분
    document.addEventListener("DOMContentLoaded", () => {
    // domcontentloaded : html 로딩 완료 시 실행되는 이벤트
        window.onSpotifyWebPlaybackSDKReady = () => {
            console.log('Spotify Web Playback SDK가 성공적으로 로드되었습니다.');
            player = new Spotify.Player({
                name: 'Spotipie Web Player',
                getOAuthToken: cb => { cb(accessToken); },
                volume: 0.5
            });

            player.addListener('ready', ({ device_id }) => {
                console.log('Ready with Device ID', device_id);
                window.deviceId = device_id; // deviceId를 전역 변수로 설정
                isPlayerReady = true; // 플레이어 준비 상태 업데이트
            });

            player.connect();
            // 플레이어를 spotify와 연결
        };

        // 로컬 스토리지에서 저장된 트랙을 가져온다.
        const savedTracks = JSON.parse(localStorage.getItem('savedTracks')) || [];
        const container = document.getElementById('savedTracksContainer');

        if (savedTracks.length > 0) {
            savedTracks.forEach(track => {
                const trackDiv = document.createElement('div');
                trackDiv.className = 'col-md-3 mb-4';
                trackDiv.innerHTML = `
                    <div class="border p-3 text-center" style="height: 350px; display: flex; flex-direction: column; justify-content: space-between;">
                        ${track.album_cover ? `<img src="${track.album_cover}" alt="${track.name}" class="img-fluid mb-2" style="max-height: 150px; object-fit: cover;">` : '<h5>커버 이미지 없음</h5>'}
                        <h2 class="h5">${track.name} - ${track.artist}</h2>
                        <div class="d-flex justify-content-center align-items-center mt-2">
                            <button onclick="playTrack('${track.uri}')" class="btn btn-circle me-2 ivory-button">Play</button>
                            <button class="delete btn btn-circle ivory-button" data-uri="${track.uri}">삭제</button>
                        </div>
                    </div>
                `;
                container.appendChild(trackDiv);
                // appendchild는 부모 요소에 자식 요소를 추가하는 메서드
            });

            // 삭제 버튼 클릭 이벤트 리스너
            const deleteButtons = document.querySelectorAll('.delete');
            // .delete 클래스 가진 버튼들 선택하고 클릭 이벤트 리스너 추가
            deleteButtons.forEach(button => {
                button.addEventListener('click', function() {
                    const trackUri = this.getAttribute('data-uri');
                    if (confirm("정말로 삭제하시겠습니까?")) {
                        deleteTrack(trackUri);
                        // 삭제 확인시 deleTrack 함수 호출
                    }
                });
            });
        } else {
            container.innerHTML = '<p>저장된 트랙이 없습니다.</p>';
        }
    });

    // 트랙 재생 함수
    window.playTrack = (trackUri) => {
        if (!window.deviceId) {
            console.error('Device ID is not available. Please wait until the player is ready.');
            return;
        }

        fetch("https://api.spotify.com/v1/me/player/play?device_id=" + window.deviceId, {
            method: 'PUT',
            body: JSON.stringify({ uris: [trackUri] }),
            headers: {
                'Content-Type': 'application/json',
                'Authorization': `Bearer ${accessToken}`
            }
        }).then(response => {
            if (response.status === 204) {
                console.log('Track is playing');
            } else {
                response.json().then(data => {
                    console.log('Failed to play track:', response.status, data);
                });
            }
        }).catch(error => {
            console.error('Error playing track:', error);
        });
    };

    // 트랙 삭제 함수
    function deleteTrack(trackUri) {
        // 로컬 스토리지에서 저장된 트랙을 삭제합니다.
        let savedTracks = JSON.parse(localStorage.getItem('savedTracks')) || [];
        savedTracks = savedTracks.filter(track => track.uri !== trackUri); // 선택한 트랙 제거
        localStorage.setItem('savedTracks', JSON.stringify(savedTracks)); // 업데이트된 트랙 저장

        alert('곡이 삭제되었습니다!');
        location.reload();  // 페이지 새로고침
    }
</script>
<style>
    .ivory-button {
        background-color: #F8F9FA;
        color: black;
    }
</style>
{% endblock %}

templates/spotipie/play_track.html
{% extends 'base.html' %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <!-- 사이드바 -->
        <div class="col-md-2" style="background-color: #f0f0f0; padding: 20px; height: 100vh; position: sticky; top: 0; overflow-y: auto;">
            <ul class="list-unstyled">
                <li>
                    <a href="{% url 'spotipie:index' %}" class="d-block mb-3" style="text-decoration: none; color: #333; font-size: 1.2em;">
                        홈
                    </a>
                </li>
                <li>
                    <a href="{% url 'spotipie:my_library'%}" class="d-block mb-3" style="text-decoration: none; color: #333; font-size: 1.2em;">
                        내 라이브러리
                    </a>
                </li>
            </ul>
        </div>

        <!-- 콘텐츠 영역 -->
        <div class="col-md-10">
            <h1 class="text-center">{{ track.name }}</h1>
            <div class="text-center mb-4">
                {% if track.album.images %}
                    <img src="{{ track.album.images.0.url }}" alt="{{ track.name }}" class="img-fluid" style="max-height: 300px; object-fit: cover;">
                {% else %}
                    <h5>커버 이미지 없음</h5>
                {% endif %}
                <p><strong>아티스트:</strong> {{ track.artists.0.name }}</p>
                <p><strong>앨범:</strong> {{ track.album.name }}</p>
                <p><strong>발매일:</strong> {{ track.album.release_date }}</p>
                <p><strong>트랙 길이:</strong> {{ track.duration_ms|floatformat:0 }} ms</p>
                <a href="{% url 'spotipie:index' %}" class="btn btn-secondary">다시 검색하기</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/spotipie/search_result.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <!-- 사이드바 -->
        <div class="col-md-2" style="background-color: #f0f0f0; padding: 20px; height: 100vh; position: sticky; top: 0; overflow-y: auto;">
            <ul class="list-unstyled">
                <li>
                    <a href="{% url 'spotipie:index' %}" class="d-block mb-3" style="text-decoration: none; color: #333; font-size: 1.2em;">홈</a>
                </li>
                <li>
                    <a href="{% url 'spotipie:my_library'%}" class="d-block mb-3" style="text-decoration: none; color: #333; font-size: 1.2em;">내 라이브러리</a>
                </li>
            </ul>
        </div>

        <!-- 콘텐츠 영역 -->
        <div class="col-md-10">
            <h1 class="text-center">SPOTIPIE</h1>

            {% if tracks %}
                <form method="get" action="{% url 'spotipie:search' %}" class="d-flex mb-4">
                    <input type="text" name="query" placeholder="노래 제목 또는 아티스트를 입력하세요" class="form-control me-2">
                    <button type="submit" class="ivory-button">검색</button>
                </form>
                <div class="row">
                    {% for track in tracks %}
                    <div class="col-md-3 mb-4">
                        <div class="border p-3 text-center" style="height: 350px; display: flex; flex-direction: column; justify-content: space-between;">
                            {% if track.album.images %}
                                <img src="{{ track.album.images.0.url }}" alt="{{ track.name }}" class="img-fluid mb-2" style="max-height: 150px; object-fit: cover;">
                            {% else %}
                                <h5>커버 이미지 없음</h5>
                            {% endif %}
                            <h2 class="h5">{{ track.name }} - {{ track.artists.0.name }}</h2>
                            <div class="d-flex justify-content-center align-items-center mt-2">
                                <button onclick="playTrack('{{ track.uri }}')" class="btn btn-circle me-2 ivory-button">Play</button>
                                <button onclick="saveTrack('{{ track.uri }}', '{{ track.name }}', '{{ track.artists.0.name }}', '{{ track.album.images.0.url }}')" class="btn btn-circle ivory-button">저장</button>
                            </div>
                            <a href="{% url 'spotipie:play_track' track.id %}" class="btn btn-white mt-0">곡 정보</a>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            {% else %}
                <p>트랙을 찾을 수 없습니다. 토큰이 만료되었는지 확인하세요.</p>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

{% block script %}
<script src="https://sdk.scdn.co/spotify-player.js"></script>

<script>
    const accessToken = "{{ access_token }}";

    document.addEventListener("DOMContentLoaded", () => {
        window.onSpotifyWebPlaybackSDKReady = () => {
            player = new Spotify.Player({
                name: 'Spotipie Web Player',
                getOAuthToken: cb => { cb(accessToken); },
                volume: 0.5
            });

            player.addListener('ready', ({ device_id }) => {
                console.log('Ready with Device ID', device_id);
                window.deviceId = device_id; // deviceId를 전역 변수로 설정
            });

            player.connect();

            // playTrack 함수 정의
            window.playTrack = (trackUri) => {
                if (!window.deviceId) {
                    console.error('Device ID is not available. Please wait until the player is ready.');
                    return;
                }

                fetch("https://api.spotify.com/v1/me/player/play?device_id=" + window.deviceId, {
                    method: 'PUT',
                    body: JSON.stringify({ uris: [trackUri] }),
                    headers: {
                        'Content-Type': 'application/json',
                        'Authorization': `Bearer ${accessToken}`
                    }
                }).then(response => {
                    if (response.status === 204) {
                        console.log('Track is playing');
                    } else {
                        response.json().then(data => {
                            console.log('Failed to play track:', response.status, data);
                        });
                    }
                }).catch(error => {
                    console.error('Error playing track:', error);
                });
            };
        };

        // 검색된 트랙을 저장하는 함수
        window.saveTrack = (trackUri, trackName, trackArtist, albumCover) => {
            const savedTracks = JSON.parse(localStorage.getItem('savedTracks')) || [];

            // 저장된 곡인지 확인
            const isTrackAlreadySaved = savedTracks.some(track => track.uri === trackUri);

            if (isTrackAlreadySaved) {
                alert('이미 저장된 곡입니다.');
                return;
            }

            const track = {
                uri: trackUri,
                name: trackName,
                artist: trackArtist,
                album_cover: albumCover
            };
            savedTracks.push(track);
            localStorage.setItem('savedTracks', JSON.stringify(savedTracks));
            alert('곡이 라이브러리에 저장되었습니다!');
        };
    });
</script>
<style>
    .ivory-button{
    background-color: #F8F9FA;
    color: black;
    }
</style>

{% endblock %}